### ISSUE TITLE
missing fedora 25 support - how can I contribute help?

### ISSUE THREAD

**Issue by eldergabriel** [kuboosoft/postinstallerf#12]
As a developer who loves Fedora and really likes PostinstallerF, what is needed to bring PostinstallerF up to date for Fedora 25 support? What is the best way to collaborate with you and help make this happen (sooner, rather than later)?

**Comment by kuboosoft** [comment]
@eldergabriel Hi!! sorry the delay (personal problems); well, Do you want collaborate; is simple; we needs maintainers; actually I am collaborating in the [unitedrpms project](https://unitedrpms.github.io/) ( I migrated various packages from postinstallerf); then postinstallerf needs packers as unitedrpms. PostinstallerF  packages works 100% with rpmfusion, but is rebuilt for unitedrpms project.... imagines!! 2 works, is a serious problem for me. Actually I am using a new infraestructure in unitedrpms and I am thinking implement in postinstallerf. About the metadata, you only needs open Postinstallerf  (about 1 hour) and share your metadata $HOME/.local/share/app-install-data-postinstallerf/index/ 

I am updating and rebuilding the packages, some packages was added to repository.... ;)
