### ISSUE TITLE
Broken repomd.xml in Fedora 21

### ISSUE THREAD

**Issue by ktomov** [kuboosoft/postinstallerf#3]
It looks like something happened with Duke's university mirror. When I try to yum update/yum search/yum install, I get the following: Error: requested datatype primary not available

I've disabled all repositories and it looks like the postinstaller's is the problematic one. 

Downloaded manually repomd.xml from here http://sourceforge.net/projects/postinstaller/files/fedora/releases/21/x86_64/repodata/ and on the second line there is this <repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">

The problem is that http://linux.duke.edu/metadata/repo redirects to http://sites.duke.edu/linuxmetadata/repo which gives 404 error. 

I've disabled postinstaller repo until this is resolved, because yum is unusable due to that error.

**Comment by kuboosoft** [comment]
su
yum clean metadata && yum -y update

You need update the metadata... It is a common problem, when we updated the repository.
