### ISSUE TITLE
possible translation bug

### ISSUE THREAD

**Issue by jheidemann** [kuboosoft/postinstallerf#4]
Your README.md  translates "software that Fedora doesn't include by default" as "software que no se incluye por defecto".  I am not a native speaker of Spanish, but I think "defecto" means the "failure" sense of default, and you want the word "predeterminado" instead, to get the "installed for you" sense.  (Or likely there is something else more idomatic.)

**Comment by kuboosoft** [comment]
Don't worry, thanks for the report :)

**Comment by kuboosoft** [comment]
solved ;)
