### ISSUE TITLE
Cannot install on Fedora 23

### ISSUE THREAD

**Issue by mboisvertdupras** [kuboosoft/postinstallerf#5]
Trying to install with the provided commands returns this error:
`warning: /var/cache/dnf/postinstallerf-updates-7639258047faf229/packages/postinstallerf-1.5-37.20151028gitd5589f3.fc23.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 73edaa09: NOKEY
Status code: 404 for http://sourceforge.net/projects/postinstaller/files/fedora/releases/23/x86_64/RPM-GPG-KEY-postinstallerf`

**Comment by kuboosoft** [comment]
@Marc-Boisvert-Dupras  Thanks! I completely forgot upload the GPG-KEY; fixed, enjoy!
