### ISSUE TITLE
Move the repo definition and gpg key to a postinstallerf-release RPM

### ISSUE THREAD

**Issue by tyll** [kuboosoft/postinstallerf#6]
You recently enabled gpg verification in the postinstallerf repo definition, this is great. However, since users copied the file to their filesystem, their yum config file will not be updated. Therefore please move the necessary files to a release RPM and then make sure that all users will install the release RPM/get their repo config file updated.

**Comment by kuboosoft** [comment]
don't worry the rpm replace the old repository ;)
