### ISSUE TITLE
GPG key https location is redirected to plain http

### ISSUE THREAD

**Issue by tyll** [kuboosoft/postinstallerf#7]
Unfortunately Sourceforge redirects https URLS to http, for example

https://sourceforge.net/projects/postinstaller/files/fedora/releases/24/i386/RPM-GPG-KEY-postinstallerf

will not return the GPG key via https, but a redirect to plain http. Please host the GPG key properly via https. It seems that github would work.

**Comment by kuboosoft** [comment]
mmm. We can't change it;  because is a issue from Source Forge and your multiple servers...  we have migrated the GPG key to github.
