### ISSUE TITLE
Consider signing the repository metadata

### ISSUE THREAD

**Issue by tyll** [kuboosoft/postinstallerf#9]
The repository metadata can be signed by adding a clearsign signature of repomd.xml as repomd.xml.asc. This protects the metadata against modification by attackers. Afterwards the .repo file needs to be updated to contain `repo_gpgcheck=True` to enable this check.

**Comment by kuboosoft** [comment]
I'm not a expert in repositories but, I was reading I can implement it. Usually I only use "createrepo"... well I use some automatic script (made my life easy) :) only I need add some lines...  If you can verify in the next update (1 or 2 days) great. 
rawhide? you can test now... only change the repository and install Opera browser :)
Ironic but Fedora doesn't use repo_gpgcheck, why?. Well enabled now :)
